s0lst1c3/eaphammer

kali-setup
The issue is that If you don't do `apt-get update` before installing, and the package list haven't been updated for a while. The kali-setup script may fail due to missing packages. The readme mentions that you have to do `apt-get update` before installing, but not everyone reads the readme.
=> Asking the user if they want to update kali package list before installing

hostapd-eaphammer/src/eap_server/eap_server_mschapv2.c, hostapd-eaphammer/src/eap_server/eap_server_ttls.c, hostapd-eaphammer/src/eaphammer_wpe/eaphammer_wpe.c, hostapd-eaphammer/src/eaphammer_wpe/eaphammer_wpe.h
This fixes a bug where MSCHAPv2 challenge hashes are incorrectly calculated if the user name has a domain name prepended.
=> Calculate correct MSCHAPv2 challenge hash when username includes domain

core/__init__.py, core/interface.py, core/utils.py, eaphammer
Added Interface class in core/interface.py that is now being used to manage the state of network interfaces. Note that the Interface class does not maintain a state itself at this time, other than the name of the interface that it is currently managing.
Additionally, within the main eaphammer file, command line options are now assigned to variables at the top of each function, rather than accessed directly from the global options dictionary. This change was made to improve code clarity.
=> Added Interface class in core/interface.py

core/__init__.py, core/interface.py, core/utils.py, eaphammer, settings/__init__.py
Added Interface class in core/interface.py that is now being used to manage the state of network interfaces. Note that the Interface class does not maintain a state itself at this time, other than the name of the interface that it is currently managing.
Additionally, within the main eaphammer file, command line options are now assigned to variables at the top of each function, rather than accessed directly from the global options dictionary. This change was made to improve code clarity.
Version bump to 0.2.6.
=> Added Interface class in core/interface.py (this time with version bump)

eaphammer
Currently on kali.linux.2018.4 release install.
from queue import Queue doesn't work if it's on python 2.7.
proposed change to the following:
from multiprocessing import Queue
This worked for me.
=> eaphammer script change

README.md
Updated the hostapd-eaphammer path of the repo to the new /local directory
=> Fixed hostapd-eaphammer path

README.md, local/hostapd-eaphammer/src/eap_server/eap_server_md5.c, local/hostapd-eaphammer/src/eap_server/eap_server_mschapv2.c, local/hostapd-eaphammer/src/eap_server/eap_server_ttls.c, local/hostapd-eaphammer/src/eaphammer_wpe/eaphammer_wpe.c, local/hostapd-eaphammer/src/eaphammer_wpe/eaphammer_wpe.h
Support for the following EAP types has been added:
- EAP-MD5
- EAP-PEAP/MD5
- EAP-TTLS/MD5
=> Eap md5 logging

Changelog, README.md, __version__.py, core/cli.py, core/hostapd_config.py, settings/core/hostapd.ini
Added support for rogue AP attacks against networks that use OWE and OWE Transition Mode. Resolves #100. Resolves #101.
=> Add Support for OWE, OWE Transition Mode

Changelog, README.md, __version__.py, core/hostapd_config.py, settings/paths.py
Hostapd ctrl_interface name randomly generated to support multiple concurrent eaphammer instances, given absolute path
=> Hostapd ctrl_interfac abspath fix

kali-dependencies.txt, kali-setup
- kali-setup - Removed calls to apt-update, apt-upgrade and replaced with warning (apt-listchanges is called by default on latest Kali version, and is not meant for unattended use).
- kali-dependencies.txt - Added python3-pip as explicit dependency.
Resolves #146
Resolves #145|
Resolves #130
=> Fixed Kali setup scripts, deps file

local/hostapd-eaphammer/src/eap_server/eap_server.c
This fixes memory leaks with 4 different code paths in `eap_user_get`:
* if `user2` allocations fails, `user` is never freed (possible, but unlikely)
* if the first `get_eap_user` call fails, `user2` is not freed
* if the second `get_eap_user` call fails, `user2` and its dynamically allocated members are not freed
* `user2` is never freed in the nominal case
=> Fix several memory leaks in eap_user_get

core/wpa_supplicant.py
Hi Gabriel,
during my latest usage of EAP password spray I encountered the following:
```
./eaphammer --eap-spray --interface-pool wlan0 --essid 'someESSID' --password Password123 --user-list /root/users.txt 
[.. snip ..]
[*] Root privs confirmed! 8D
[wlan0] Trying credentials: test:Password123@someESSID
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/root/Downloads/eaphammer/core/eap_spray/worker.py", line 34, in _start
if wpa_supplicant.test_creds():
File "/root/Downloads/eaphammer/core/wpa_supplicant.py", line 18, in test_creds
print(line.replace('%s:' % self.interface, '[%s]' % …
```
=> EAP password spray method: small fix for bytes error

Changelog, README.md, __version__.py, eaphammer, pip.req
Fixed gevent issues by modifying eaphammer to explicitly call Python 3.8. Modified pip.req to… require a version of gevent greater than 1.5.0.
=> Fix gevent python 3.8 related fuckery

core/autocrack.py
This fixes the issue #184 by validating the challenge and response.
Formatting the fifo with known format or encoding each part before inserting in fifo could help the integrity. However, this would require modification to every module using the fifo and would result in more storage usage and time.
=> Autocrack fix

payload_generator
It fixes the following error when running the payload_generator script:
... 
```
/eaphammer/payload_generator", line 49
print s.execute()
^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```
=> fixing-missing-parentheses-on-print

core/payloads.py, payload_generator
It will fix the following error generated by the /core/payloads.py file:
```
... core/payloads.py", line 17, in execute
return 'powershell.exe -nop -w hidden -encodedCommand '+base64.b64encode(('''ipmo ScheduledTasks
TypeError: can only concatenate str (not "bytes") to str
```
=> fixing 'TypeError: can only concatenate str, not bytes to str'

README.md
Originally: `Parot OS`
Now: `Parrot OS`
=> Fix typo in /README.md

local/hcxdumptool/hcxdumptool.c
Using `kali-setup` script in a Debian 11 (Testing), error:
<samp>error: ‘SIOCGSTAMP’ undeclared (first use in this function); did you mean ‘SIOCGARP’</samp>
Fix: `sockios.h` wasn't  included
=> `sockios.h` wasn't  included

core/cli.py, core/iw_parse/iw_parse.py, core/strtobool.py, core/wskeyloggerd/app.py, eaphammer
It fixes https://github.com/s0lst1c3/eaphammer/issues/219
=> Support for Python 3.12

Changelog, README.md, __version__.py, core/cli.py, core/iw_parse/iw_parse.py, core/strtobool.py, core/utils.py, core/wskeyloggerd/app.py, eaphammer, kali-dependencies.txt, kali-setup, local/hostapd-eaphammer/hostapd/config_file.c, local/hostapd-eaphammer/src/eap_server/eap_server_gtc.c, local/hostapd-eaphammer/src/eap_server/eap_server_md5.c, parrot-dependencies.txt, parrot-setup, pip.req, raspbian-dependencies.txt, raspbian-setup, ubuntu-unattended-setup
Bug and build fixes:
- Fixed hostapd-eaphammer_lib build issues.
- The system-wide package manager (i.e. apt) is now the single source of truth for dependencies, including Python. Sounds stupid, but realistically it's probably the most stable option until we start managing the Python portions of this thing with something that isn't archaic (like Poetry) and published as a proper PyPi package.
- Removed unused Python dependencies: jinja2, pyquery
- Added support for Python 3.12 (Credit: github.com/D3vil0p3r)
- Updated README to reflect use of apt during installation instructions (Credit: github.com/readloud)
- Added wget to dependencies (Credit: github/pes-soft)
Resolutions:
- Fixes #207
- Fixes #209
- Fixes #217
- Fixes #218
- Fixes #219
=> Fix build issues - Sept 22nd 2024
